### ISSUE TITLE
Can't reinstall

### ISSUE THREAD

**Issue by fmate2006** [GabrieleGiuseppini/Floating-Sandbox#13]
I installed it, but then I realized that it was missing textures. So I deleted it, then launched the installer but it said that it is already installed. I was done with this in under 2 minutes. Thanks. (sarcasm)

**Comment by GabrieleGiuseppini** [comment]
Hi, when you say "I deleted it", do you mean that you wiped the folder out? If that's the case, that is not how Windows works. After running an installer, Windows remembers that a product has been installed and the only way to make it forget about it is to uninstall the software, which you can do from the control panel (choose "Programs", find "Floating Sandbox", and choose "Uninstall").

**Comment by GabrieleGiuseppini** [comment]
By the way, what textures were missing? If the installer completed successfully, then all files have been copied to the host. If all you could see were clouds but no ship, then you encountered a well-known issue with certain graphics cards that has already been fixed in 1.10.0, which will be released this coming weekend.

**Comment by fmate2006** [comment]
> By the way, what textures were missing? If the installer completed successfully, then all files have been copied to the host. If all you could see were clouds but no ship, then you encountered a well-known issue with certain graphics cards that has already been fixed in 1.10.0, which will be released this coming weekend.

Oh yes, that was the problem. Thank you

**Comment by GabrieleGiuseppini** [comment]
Glad to hear that. Check the game page this weekend, the release will be out.

**Comment by GabrieleGiuseppini** [comment]
Glad to hear that. Check the game page this weekend, the release will be out any time soon!

**Comment by fmate2006** [comment]
Actually I may know what is causing the nothing-but-clouds glitch.
Every single image in the game looks like this.
![photoshop-error](https://user-images.githubusercontent.com/38377724/55288259-27987680-53b5-11e9-9580-6579bc8b705e.png)
