### ISSUE TITLE
Fails to build under Linux #2

### ISSUE THREAD

**Issue by h6899** [GabrieleGiuseppini/Floating-Sandbox#19]
`make -j4
[  3%] Built target gtest
[  9%] Built target GameCoreLib
[ 12%] Built target gmock
[ 12%] Built target gtest_main
[ 15%] Built target GameOpenGLLib
[ 20%] Built target GPUCalcLib
[ 24%] Built target GPUCalcTest
[ 25%] Building CXX object Game/CMakeFiles/GameLib.dir/GameController.cpp.o
[ 26%] Building CXX object Game/CMakeFiles/GameLib.dir/GameController_StateMachines.cpp.o
[ 27%] Building CXX object Game/CMakeFiles/GameLib.dir/ShipBuilder.cpp.o
[ 28%] Building CXX object Game/CMakeFiles/GameLib.dir/ShipPreview.cpp.o
[ 28%] Building CXX object Game/CMakeFiles/GameLib.dir/StatusText.cpp.o
In file included from /home/h6899/Documents/floating/Floating-Sandbox/Game/ElectricalElements.h:12,
                 from /home/h6899/Documents/floating/Floating-Sandbox/Game/Physics.h:30,
                 from /home/h6899/Documents/floating/Floating-Sandbox/Game/GameController.h:13,
                 from /home/h6899/Documents/floating/Floating-Sandbox/Game/GameController.cpp:6:
/home/h6899/Documents/floating/Floating-Sandbox/GameCore/../GameCore/GameWallClock.h: In member function ‘float GameWallClock::ProgressSince(GameWallClock::time_point, TDuration) const’:
/home/h6899/Documents/floating/Floating-Sandbox/GameCore/../GameCore/GameWallClock.h:80:50: error: request for member ‘count’ in ‘((const GameWallClock*)this)->GameWallClock::ElapsedAsFloat(previousTimePoint)’, which is of non-class type ‘float’
   80 |         return ElapsedAsFloat(previousTimePoint).count()
      |                                                  ^~~~~
In file included from /home/h6899/Documents/floating/Floating-Sandbox/Game/ElectricalElements.h:12,
                 from /home/h6899/Documents/floating/Floating-Sandbox/Game/Physics.h:30,
                 from /home/h6899/Documents/floating/Floating-Sandbox/Game/GameController.h:13,
                 from /home/h6899/Documents/floating/Floating-Sandbox/Game/GameController_StateMachines.cpp:6:
/home/h6899/Documents/floating/Floating-Sandbox/GameCore/../GameCore/GameWallClock.h: In member function ‘float GameWallClock::ProgressSince(GameWallClock::time_point, TDuration) const’:
/home/h6899/Documents/floating/Floating-Sandbox/GameCore/../GameCore/GameWallClock.h:80:50: error: request for member ‘count’ in ‘((const GameWallClock*)this)->GameWallClock::ElapsedAsFloat(previousTimePoint)’, which is of non-class type ‘float’
   80 |         return ElapsedAsFloat(previousTimePoint).count()
      |                                                  ^~~~~
In file included from /home/h6899/Documents/floating/Floating-Sandbox/Game/ElectricalElements.h:12,
                 from /home/h6899/Documents/floating/Floating-Sandbox/Game/Physics.h:30,
                 from /home/h6899/Documents/floating/Floating-Sandbox/Game/ShipBuilder.h:10,
                 from /home/h6899/Documents/floating/Floating-Sandbox/Game/ShipBuilder.cpp:8:
/home/h6899/Documents/floating/Floating-Sandbox/GameCore/../GameCore/GameWallClock.h: In member function ‘float GameWallClock::ProgressSince(GameWallClock::time_point, TDuration) const’:
/home/h6899/Documents/floating/Floating-Sandbox/GameCore/../GameCore/GameWallClock.h:80:50: error: request for member ‘count’ in ‘((const GameWallClock*)this)->GameWallClock::ElapsedAsFloat(previousTimePoint)’, which is of non-class type ‘float’
   80 |         return ElapsedAsFloat(previousTimePoint).count()
      |                                                  ^~~~~
In file included from /home/h6899/Documents/floating/Floating-Sandbox/Game/Physics.h:44,
                 from /home/h6899/Documents/floating/Floating-Sandbox/Game/GameController.h:13,
                 from /home/h6899/Documents/floating/Floating-Sandbox/Game/GameController.cpp:6:
/home/h6899/Documents/floating/Floating-Sandbox/Game/Bombs.h: At global scope:
/home/h6899/Documents/floating/Floating-Sandbox/Game/Bombs.h:241:14: error: expected nested-name-specifier before ‘LocalBombId’
  241 |     typename LocalBombId mNextLocalBombId;
      |              ^~~~~~~~~~~
/home/h6899/Documents/floating/Floating-Sandbox/Game/Bombs.h:241:14: error: expected ‘;’ at end of member declaration
  241 |     typename LocalBombId mNextLocalBombId;
      |              ^~~~~~~~~~~
      |                         ;
In file included from /home/h6899/Documents/floating/Floating-Sandbox/Game/Physics.h:44,
                 from /home/h6899/Documents/floating/Floating-Sandbox/Game/GameController.h:13,
                 from /home/h6899/Documents/floating/Floating-Sandbox/Game/GameController_StateMachines.cpp:6:
/home/h6899/Documents/floating/Floating-Sandbox/Game/Bombs.h: At global scope:
/home/h6899/Documents/floating/Floating-Sandbox/Game/Bombs.h:241:14: error: expected nested-name-specifier before ‘LocalBombId’
  241 |     typename LocalBombId mNextLocalBombId;
      |              ^~~~~~~~~~~
/home/h6899/Documents/floating/Floating-Sandbox/Game/Bombs.h:241:14: error: expected ‘;’ at end of member declaration
  241 |     typename LocalBombId mNextLocalBombId;
      |              ^~~~~~~~~~~
      |                         ;
/home/h6899/Documents/floating/Floating-Sandbox/Game/Bombs.h:241:26: error: ‘mNextLocalBombId’ does not name a type; did you mean ‘LocalBombId’?
  241 |     typename LocalBombId mNextLocalBombId;
      |                          ^~~~~~~~~~~~~~~~
      |                          LocalBombId
In file included from /home/h6899/Documents/floating/Floating-Sandbox/Game/Physics.h:44,
                 from /home/h6899/Documents/floating/Floating-Sandbox/Game/GameController.h:13,
                 from /home/h6899/Documents/floating/Floating-Sandbox/Game/GameController.cpp:6:
/home/h6899/Documents/floating/Floating-Sandbox/Game/Bombs.h: In constructor ‘Physics::Bombs::Bombs(Physics::World&, ShipId, std::shared_ptr<GameEventDispatcher>, Physics::Bomb::IPhysicsHandler&, Physics::Points&, Physics::Springs&)’:
/home/h6899/Documents/floating/Floating-Sandbox/Game/Bombs.h:47:11: error: class ‘Physics::Bombs’ does not have any field named ‘mNextLocalBombId’
   47 |         , mNextLocalBombId(0)
      |           ^~~~~~~~~~~~~~~~
/home/h6899/Documents/floating/Floating-Sandbox/Game/Bombs.h:241:26: error: ‘mNextLocalBombId’ does not name a type; did you mean ‘LocalBombId’?
  241 |     typename LocalBombId mNextLocalBombId;
      |                          ^~~~~~~~~~~~~~~~
      |                          LocalBombId
In file included from /home/h6899/Documents/floating/Floating-Sandbox/Game/Physics.h:44,
                 from /home/h6899/Documents/floating/Floating-Sandbox/Game/GameController.h:13,
                 from /home/h6899/Documents/floating/Floating-Sandbox/Game/GameController_StateMachines.cpp:6:
/home/h6899/Documents/floating/Floating-Sandbox/Game/Bombs.h: In constructor ‘Physics::Bombs::Bombs(Physics::World&, ShipId, std::shared_ptr<GameEventDispatcher>, Physics::Bomb::IPhysicsHandler&, Physics::Points&, Physics::Springs&)’:
/home/h6899/Documents/floating/Floating-Sandbox/Game/Bombs.h:47:11: error: class ‘Physics::Bombs’ does not have any field named ‘mNextLocalBombId’
   47 |         , mNextLocalBombId(0)
      |           ^~~~~~~~~~~~~~~~
In file included from /home/h6899/Documents/floating/Floating-Sandbox/Game/Physics.h:44,
                 from /home/h6899/Documents/floating/Floating-Sandbox/Game/GameController.h:13,
                 from /home/h6899/Documents/floating/Floating-Sandbox/Game/GameController_StateMachines.cpp:6:
/home/h6899/Documents/floating/Floating-Sandbox/Game/Bombs.h: In member function ‘bool Physics::Bombs::ToggleBombAt(const vec2f&, const GameParameters&)’:
/home/h6899/Documents/floating/Floating-Sandbox/Game/Bombs.h:179:37: error: ‘mNextLocalBombId’ was not declared in this scope; did you mean ‘LocalBombId’?
  179 |                     BombId(mShipId, mNextLocalBombId++),
      |                                     ^~~~~~~~~~~~~~~~
      |                                     LocalBombId
In file included from /home/h6899/Documents/floating/Floating-Sandbox/Game/Physics.h:44,
                 from /home/h6899/Documents/floating/Floating-Sandbox/Game/GameController.h:13,
                 from /home/h6899/Documents/floating/Floating-Sandbox/Game/GameController.cpp:6:
/home/h6899/Documents/floating/Floating-Sandbox/Game/Bombs.h: In member function ‘bool Physics::Bombs::ToggleBombAt(const vec2f&, const GameParameters&)’:
/home/h6899/Documents/floating/Floating-Sandbox/Game/Bombs.h:179:37: error: ‘mNextLocalBombId’ was not declared in this scope; did you mean ‘LocalBombId’?
  179 |                     BombId(mShipId, mNextLocalBombId++),
      |                                     ^~~~~~~~~~~~~~~~
      |                                     LocalBombId
In file included from /home/h6899/Documents/floating/Floating-Sandbox/Game/Physics.h:44,
                 from /home/h6899/Documents/floating/Floating-Sandbox/Game/ShipBuilder.h:10,
                 from /home/h6899/Documents/floating/Floating-Sandbox/Game/ShipBuilder.cpp:8:
/home/h6899/Documents/floating/Floating-Sandbox/Game/Bombs.h: At global scope:
/home/h6899/Documents/floating/Floating-Sandbox/Game/Bombs.h:241:14: error: expected nested-name-specifier before ‘LocalBombId’
  241 |     typename LocalBombId mNextLocalBombId;
      |              ^~~~~~~~~~~
/home/h6899/Documents/floating/Floating-Sandbox/Game/Bombs.h:241:14: error: expected ‘;’ at end of member declaration
  241 |     typename LocalBombId mNextLocalBombId;
      |              ^~~~~~~~~~~
      |                         ;
/home/h6899/Documents/floating/Floating-Sandbox/Game/Bombs.h:241:26: error: ‘mNextLocalBombId’ does not name a type; did you mean ‘LocalBombId’?
  241 |     typename LocalBombId mNextLocalBombId;
      |                          ^~~~~~~~~~~~~~~~
      |                          LocalBombId
In file included from /home/h6899/Documents/floating/Floating-Sandbox/Game/Physics.h:44,
                 from /home/h6899/Documents/floating/Floating-Sandbox/Game/ShipBuilder.h:10,
                 from /home/h6899/Documents/floating/Floating-Sandbox/Game/ShipBuilder.cpp:8:
/home/h6899/Documents/floating/Floating-Sandbox/Game/Bombs.h: In constructor ‘Physics::Bombs::Bombs(Physics::World&, ShipId, std::shared_ptr<GameEventDispatcher>, Physics::Bomb::IPhysicsHandler&, Physics::Points&, Physics::Springs&)’:
/home/h6899/Documents/floating/Floating-Sandbox/Game/Bombs.h:47:11: error: class ‘Physics::Bombs’ does not have any field named ‘mNextLocalBombId’
   47 |         , mNextLocalBombId(0)
      |           ^~~~~~~~~~~~~~~~
In file included from /home/h6899/Documents/floating/Floating-Sandbox/Game/Physics.h:44,
                 from /home/h6899/Documents/floating/Floating-Sandbox/Game/ShipBuilder.h:10,
                 from /home/h6899/Documents/floating/Floating-Sandbox/Game/ShipBuilder.cpp:8:
/home/h6899/Documents/floating/Floating-Sandbox/Game/Bombs.h: In member function ‘bool Physics::Bombs::ToggleBombAt(const vec2f&, const GameParameters&)’:
/home/h6899/Documents/floating/Floating-Sandbox/Game/Bombs.h:179:37: error: ‘mNextLocalBombId’ was not declared in this scope; did you mean ‘LocalBombId’?
  179 |                     BombId(mShipId, mNextLocalBombId++),
      |                                     ^~~~~~~~~~~~~~~~
      |                                     LocalBombId
make[2]: *** [Game/CMakeFiles/GameLib.dir/build.make:76: Game/CMakeFiles/GameLib.dir/GameController_StateMachines.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [Game/CMakeFiles/GameLib.dir/build.make:63: Game/CMakeFiles/GameLib.dir/GameController.cpp.o] Error 1
make[2]: *** [Game/CMakeFiles/GameLib.dir/build.make:141: Game/CMakeFiles/GameLib.dir/ShipBuilder.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:385: Game/CMakeFiles/GameLib.dir/all] Error 2
make: *** [Makefile:130: all] Error 2`

**Comment by GabrieleGiuseppini** [comment]
Hey, thanks so much for reporting this - again. I'll be on it shortly.

**Comment by GabrieleGiuseppini** [comment]
Hi, I've pushed fixed for the two errors above, they are under the 1.13_optimizations branch. Let me know which other errors you get.

**Comment by h6899** [comment]
`[  3%] Built target gtest
[  9%] Built target GameCoreLib
[ 12%] Built target gmock
[ 12%] Built target gtest_main
[ 15%] Built target GameOpenGLLib
[ 19%] Built target GPUCalcLib
[ 23%] Built target GPUCalcTest
[ 24%] Building CXX object Game/CMakeFiles/GameLib.dir/GameController.cpp.o
[ 25%] Building CXX object Game/CMakeFiles/GameLib.dir/GameController_StateMachines.cpp.o
[ 25%] Building CXX object Game/CMakeFiles/GameLib.dir/ShipBuilder.cpp.o
[ 26%] Building CXX object Game/CMakeFiles/GameLib.dir/AntiMatterBomb.cpp.o
In file included from /home/h6899/Documents/floating/Floating-Sandbox/Game/Physics.h:44,
                 from /home/h6899/Documents/floating/Floating-Sandbox/Game/ShipBuilder.h:10,
                 from /home/h6899/Documents/floating/Floating-Sandbox/Game/ShipBuilder.cpp:8:
/home/h6899/Documents/floating/Floating-Sandbox/Game/Bombs.h:242:14: error: expected nested-name-specifier before ‘LocalBombId’
  242 |     typename LocalBombId mNextLocalBombId;
      |              ^~~~~~~~~~~
/home/h6899/Documents/floating/Floating-Sandbox/Game/Bombs.h:242:14: error: expected ‘;’ at end of member declaration
  242 |     typename LocalBombId mNextLocalBombId;
      |              ^~~~~~~~~~~
      |                         ;
/home/h6899/Documents/floating/Floating-Sandbox/Game/Bombs.h:242:26: error: ‘mNextLocalBombId’ does not name a type; did you mean ‘LocalBombId’?
  242 |     typename LocalBombId mNextLocalBombId;
      |                          ^~~~~~~~~~~~~~~~
      |                          LocalBombId
In file included from /home/h6899/Documents/floating/Floating-Sandbox/Game/Physics.h:44,
                 from /home/h6899/Documents/floating/Floating-Sandbox/Game/ShipBuilder.h:10,
                 from /home/h6899/Documents/floating/Floating-Sandbox/Game/ShipBuilder.cpp:8:
/home/h6899/Documents/floating/Floating-Sandbox/Game/Bombs.h: In constructor ‘Physics::Bombs::Bombs(Physics::World&, ShipId, std::shared_ptr<GameEventDispatcher>, Physics::Bomb::IPhysicsHandler&, Physics::Points&, Physics::Springs&)’:
/home/h6899/Documents/floating/Floating-Sandbox/Game/Bombs.h:48:11: error: class ‘Physics::Bombs’ does not have any field named ‘mNextLocalBombId’
   48 |         , mNextLocalBombId(0)
      |           ^~~~~~~~~~~~~~~~
In file included from /home/h6899/Documents/floating/Floating-Sandbox/Game/Physics.h:44,
                 from /home/h6899/Documents/floating/Floating-Sandbox/Game/ShipBuilder.h:10,
                 from /home/h6899/Documents/floating/Floating-Sandbox/Game/ShipBuilder.cpp:8:
/home/h6899/Documents/floating/Floating-Sandbox/Game/Bombs.h: In member function ‘bool Physics::Bombs::ToggleBombAt(const vec2f&, const GameParameters&)’:
/home/h6899/Documents/floating/Floating-Sandbox/Game/Bombs.h:180:37: error: ‘mNextLocalBombId’ was not declared in this scope; did you mean ‘LocalBombId’?
  180 |                     BombId(mShipId, mNextLocalBombId++),
      |                                     ^~~~~~~~~~~~~~~~
      |                                     LocalBombId
In file included from /home/h6899/Documents/floating/Floating-Sandbox/Game/Physics.h:44,
                 from /home/h6899/Documents/floating/Floating-Sandbox/Game/GameController.h:13,
                 from /home/h6899/Documents/floating/Floating-Sandbox/Game/GameController.cpp:6:
/home/h6899/Documents/floating/Floating-Sandbox/Game/Bombs.h:242:14: error: expected nested-name-specifier before ‘LocalBombId’
  242 |     typename LocalBombId mNextLocalBombId;
      |              ^~~~~~~~~~~
/home/h6899/Documents/floating/Floating-Sandbox/Game/Bombs.h:242:14: error: expected ‘;’ at end of member declaration
  242 |     typename LocalBombId mNextLocalBombId;
      |              ^~~~~~~~~~~
      |                         ;
/home/h6899/Documents/floating/Floating-Sandbox/Game/Bombs.h:242:26: error: ‘mNextLocalBombId’ does not name a type; did you mean ‘LocalBombId’?
  242 |     typename LocalBombId mNextLocalBombId;
      |                          ^~~~~~~~~~~~~~~~
      |                          LocalBombId
In file included from /home/h6899/Documents/floating/Floating-Sandbox/Game/Physics.h:44,
                 from /home/h6899/Documents/floating/Floating-Sandbox/Game/GameController.h:13,
                 from /home/h6899/Documents/floating/Floating-Sandbox/Game/GameController.cpp:6:
/home/h6899/Documents/floating/Floating-Sandbox/Game/Bombs.h: In constructor ‘Physics::Bombs::Bombs(Physics::World&, ShipId, std::shared_ptr<GameEventDispatcher>, Physics::Bomb::IPhysicsHandler&, Physics::Points&, Physics::Springs&)’:
/home/h6899/Documents/floating/Floating-Sandbox/Game/Bombs.h:48:11: error: class ‘Physics::Bombs’ does not have any field named ‘mNextLocalBombId’
   48 |         , mNextLocalBombId(0)
      |           ^~~~~~~~~~~~~~~~
In file included from /home/h6899/Documents/floating/Floating-Sandbox/Game/Physics.h:44,
                 from /home/h6899/Documents/floating/Floating-Sandbox/Game/GameController.h:13,
                 from /home/h6899/Documents/floating/Floating-Sandbox/Game/GameController.cpp:6:
/home/h6899/Documents/floating/Floating-Sandbox/Game/Bombs.h: In member function ‘bool Physics::Bombs::ToggleBombAt(const vec2f&, const GameParameters&)’:
/home/h6899/Documents/floating/Floating-Sandbox/Game/Bombs.h:180:37: error: ‘mNextLocalBombId’ was not declared in this scope; did you mean ‘LocalBombId’?
  180 |                     BombId(mShipId, mNextLocalBombId++),
      |                                     ^~~~~~~~~~~~~~~~
      |                                     LocalBombId
In file included from /home/h6899/Documents/floating/Floating-Sandbox/Game/Physics.h:44,
                 from /home/h6899/Documents/floating/Floating-Sandbox/Game/AntiMatterBomb.cpp:6:
/home/h6899/Documents/floating/Floating-Sandbox/Game/Bombs.h:242:14: error: expected nested-name-specifier before ‘LocalBombId’
  242 |     typename LocalBombId mNextLocalBombId;
      |              ^~~~~~~~~~~
/home/h6899/Documents/floating/Floating-Sandbox/Game/Bombs.h:242:14: error: expected ‘;’ at end of member declaration
  242 |     typename LocalBombId mNextLocalBombId;
      |              ^~~~~~~~~~~
      |                         ;
/home/h6899/Documents/floating/Floating-Sandbox/Game/Bombs.h:242:26: error: ‘mNextLocalBombId’ does not name a type; did you mean ‘LocalBombId’?
  242 |     typename LocalBombId mNextLocalBombId;
      |                          ^~~~~~~~~~~~~~~~
      |                          LocalBombId
In file included from /home/h6899/Documents/floating/Floating-Sandbox/Game/Physics.h:44,
                 from /home/h6899/Documents/floating/Floating-Sandbox/Game/AntiMatterBomb.cpp:6:
/home/h6899/Documents/floating/Floating-Sandbox/Game/Bombs.h: In constructor ‘Physics::Bombs::Bombs(Physics::World&, ShipId, std::shared_ptr<GameEventDispatcher>, Physics::Bomb::IPhysicsHandler&, Physics::Points&, Physics::Springs&)’:
/home/h6899/Documents/floating/Floating-Sandbox/Game/Bombs.h:48:11: error: class ‘Physics::Bombs’ does not have any field named ‘mNextLocalBombId’
   48 |         , mNextLocalBombId(0)
      |           ^~~~~~~~~~~~~~~~
In file included from /home/h6899/Documents/floating/Floating-Sandbox/Game/Physics.h:44,
                 from /home/h6899/Documents/floating/Floating-Sandbox/Game/GameController.h:13,
                 from /home/h6899/Documents/floating/Floating-Sandbox/Game/GameController_StateMachines.cpp:6:
/home/h6899/Documents/floating/Floating-Sandbox/Game/Bombs.h:242:14: error: expected nested-name-specifier before ‘LocalBombId’
  242 |     typename LocalBombId mNextLocalBombId;
      |              ^~~~~~~~~~~
/home/h6899/Documents/floating/Floating-Sandbox/Game/Bombs.h:242:14: error: expected ‘;’ at end of member declaration
  242 |     typename LocalBombId mNextLocalBombId;
      |              ^~~~~~~~~~~
      |                         ;
/home/h6899/Documents/floating/Floating-Sandbox/Game/Bombs.h:242:26: error: ‘mNextLocalBombId’ does not name a type; did you mean ‘LocalBombId’?
  242 |     typename LocalBombId mNextLocalBombId;
      |                          ^~~~~~~~~~~~~~~~
      |                          LocalBombId
In file included from /home/h6899/Documents/floating/Floating-Sandbox/Game/Physics.h:44,
                 from /home/h6899/Documents/floating/Floating-Sandbox/Game/GameController.h:13,
                 from /home/h6899/Documents/floating/Floating-Sandbox/Game/GameController_StateMachines.cpp:6:
/home/h6899/Documents/floating/Floating-Sandbox/Game/Bombs.h: In constructor ‘Physics::Bombs::Bombs(Physics::World&, ShipId, std::shared_ptr<GameEventDispatcher>, Physics::Bomb::IPhysicsHandler&, Physics::Points&, Physics::Springs&)’:
/home/h6899/Documents/floating/Floating-Sandbox/Game/Bombs.h:48:11: error: class ‘Physics::Bombs’ does not have any field named ‘mNextLocalBombId’
   48 |         , mNextLocalBombId(0)
      |           ^~~~~~~~~~~~~~~~
In file included from /home/h6899/Documents/floating/Floating-Sandbox/Game/Physics.h:44,
                 from /home/h6899/Documents/floating/Floating-Sandbox/Game/AntiMatterBomb.cpp:6:
/home/h6899/Documents/floating/Floating-Sandbox/Game/Bombs.h: In member function ‘bool Physics::Bombs::ToggleBombAt(const vec2f&, const GameParameters&)’:
/home/h6899/Documents/floating/Floating-Sandbox/Game/Bombs.h:180:37: error: ‘mNextLocalBombId’ was not declared in this scope; did you mean ‘LocalBombId’?
  180 |                     BombId(mShipId, mNextLocalBombId++),
      |                                     ^~~~~~~~~~~~~~~~
      |                                     LocalBombId
In file included from /home/h6899/Documents/floating/Floating-Sandbox/Game/Physics.h:44,
                 from /home/h6899/Documents/floating/Floating-Sandbox/Game/GameController.h:13,
                 from /home/h6899/Documents/floating/Floating-Sandbox/Game/GameController_StateMachines.cpp:6:
/home/h6899/Documents/floating/Floating-Sandbox/Game/Bombs.h: In member function ‘bool Physics::Bombs::ToggleBombAt(const vec2f&, const GameParameters&)’:
/home/h6899/Documents/floating/Floating-Sandbox/Game/Bombs.h:180:37: error: ‘mNextLocalBombId’ was not declared in this scope; did you mean ‘LocalBombId’?
  180 |                     BombId(mShipId, mNextLocalBombId++),
      |                                     ^~~~~~~~~~~~~~~~
      |                                     LocalBombId
make[2]: *** [Game/CMakeFiles/GameLib.dir/build.make:206: Game/CMakeFiles/GameLib.dir/AntiMatterBomb.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [Game/CMakeFiles/GameLib.dir/build.make:76: Game/CMakeFiles/GameLib.dir/GameController_StateMachines.cpp.o] Error 1
make[2]: *** [Game/CMakeFiles/GameLib.dir/build.make:141: Game/CMakeFiles/GameLib.dir/ShipBuilder.cpp.o] Error 1
make[2]: *** [Game/CMakeFiles/GameLib.dir/build.make:63: Game/CMakeFiles/GameLib.dir/GameController.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:385: Game/CMakeFiles/GameLib.dir/all] Error 2
make: *** [Makefile:130: all] Error 2`

**Comment by GabrieleGiuseppini** [comment]
Uhm, pushed a fix. Can you try again?

**Comment by GabrieleGiuseppini** [comment]
Hey, I've merged into master and I'll be working from there from now on. Feel free to retry building on master.

**Comment by GabrieleGiuseppini** [comment]
Feel free to reopen if you encounter new issues after trying again.
