### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by dcahill** [GabrieleGiuseppini/Floating-Sandbox#20]
Sorry I can't find anything on the website to submit one so doing it here:

Would be awesome to add passengers who try to escape, bail water, put out fires, close watertight bulkheads, use lifeboats, etc.

But the biggest one of this is lifeboats and lifevests with a survivor counter obviously ;).

**Comment by GabrieleGiuseppini** [comment]
Hi, thanks for the suggestion!!! We have already a plan to investigate adding NPC's to the game - these would move around the ship, fall in holes, and so on.  It's gonna take a while though :-)
