### ISSUE TITLE
Flood/dry only dries

### ISSUE THREAD

**Issue by BarabasGitHub** [GabrieleGiuseppini/Floating-Sandbox#30]
I guess you press shift to access the other functionality, but I can't seem to get it to work. It just keeps flooding my ship more and more 🤣

**Comment by GabrieleGiuseppini** [comment]
Are you 100% sure? Try to bump up "Flood Quantity" from "Settings->Interactions" and see whether what seems to be flooding is in fact drying...If it still doesn't work for you, I'll send you a build with extra logging to debug this out.

**Comment by BarabasGitHub** [comment]
Ah it works, it's just really a lot slower to drain than to fill.

**Comment by GabrieleGiuseppini** [comment]
Yes, and there's an (unfortunate) reason for that. The quantity of incoming water depends on the depth, and there's no upper bound to it. The quantity of water drained from a point, instead, is capped by...the quantity of water at that point. Once you drain a point fully, it takes another simulation step to fill-in that void from its neighbours. Unless I allow it to go negative, which I wouldn't dare.

I'm having the same issue now with the pumps - it's faster to flood a tank than to drain it...any clever  ideas for this, Bas? :-)

**Comment by GabrieleGiuseppini** [comment]
Closing as at this moment this is by (not so great) design.

**Comment by BarabasGitHub** [comment]
Sorry, I have no clever ideas for this. 
Obvious things are not having the incoming water depend on the depth and making it drain water from an area (circle) instead of just a point.
