### ISSUE TITLE
Clouds move too fast

### ISSUE THREAD

**Issue by BarabasGitHub** [GabrieleGiuseppini/Floating-Sandbox#31]
Maybe they move this fast when you're actually in the clouds, but it looks a bit strange when they're in the sky and flying past at 100km/h.

**Comment by GabrieleGiuseppini** [comment]
You mean they move too fast with the default settings (i.e. wind at 20km/h)?

**Comment by BarabasGitHub** [comment]
Yes.

**Comment by GabrieleGiuseppini** [comment]
ROTFL, I see. May be you're right indeed :-)
Can you play a bit with the "Wind Speed" setting and tell me which wind speed gives clouds the speed that seems more natural to you? I can then use that to change the wind->cloud speed translation.

**Comment by BarabasGitHub** [comment]
Probably 2 or 4. 😋

**Comment by GabrieleGiuseppini** [comment]
Ok, I'm changing the wind speed -> cloud speed transformation as follows: http://fooplot.com/#W3sidHlwZSI6MCwiZXEiOiIwLjAzKnheMS43IiwiY29sb3IiOiIjMDAwMDAwIn0seyJ0eXBlIjowLCJlcSI6Ii03LzgqeCt4XjEuMTQiLCJjb2xvciI6IiMwMDAwMDAifSx7InR5cGUiOjEwMDAsIndpbmRvdyI6WyItMTcuNzUwMDAwMDAwMDAwMDUiLCI4Ni4yNDk5OTk5OTk5OTk5NyIsIi0yNC4xOTk5OTk5OTk5OTk5OTYiLCIzOS43OTk5OTk5OTk5OTk5NTUiXX1d

Old and new curves side-by-side.

**Comment by GabrieleGiuseppini** [comment]
Closed with commit to 1.14 branch - will soon merge to master.

**Comment by BarabasGitHub** [comment]
The graph doesn't tell me much, but I assume I'll look better :)
