### ISSUE TITLE
Unhandled Exception

### ISSUE THREAD

**Issue by Jonesyboy49** [GabrieleGiuseppini/Floating-Sandbox#33]
Everytime i load into Floating Sandbox,if i try to press ctrl+d to load in my settings,it says there was an unhandled exception and when i went to try and change my settings to how i normally have it using the options tab,it says again that there was an unhandled exception,this just started when i installed 1.14,ihave repaired the game,reinstalled it,nothing worked,now i am stuck playing the game with my unusual settings.

**Comment by GabrieleGiuseppini** [comment]
Hi, I think I know what's going on. Can you do this for me:
1) Go under C:\Users\<Your username>\AppData\Roaming\Floating Sandbox\Settings
2) Copy all the files there somewhere else 
3) Delete the files then
At this moment FS should restart!

If that's the case, can you please send me the files at point 2) above? This is not the first time I get a report like this and would like to figure out what's going on so I may fix this bug. Thanks so much in advance!

**Comment by GabrieleGiuseppini** [comment]
Closing - please reopen if you still experience the issue.
