### ISSUE TITLE
Image Files Are Too Large

### ISSUE THREAD

**Issue by DonFlymoor** [GabrieleGiuseppini/Floating-Sandbox#35]
Some of the .psd files are ~65 MB, such as Explosion 1, Explosion 2, Explosion 3, Explosion 4... Is it possible to convert them to some other file format? Because of these large .psd files, people with low bandwidth may have trouble cloning this repository.

**Comment by GabrieleGiuseppini** [comment]
Hi, sure - I'm gonna enable Git LFS and see if that helps. Gimme a day or two.

**Comment by DonFlymoor** [comment]
Thanks!

**Comment by GabrieleGiuseppini** [comment]
Actually, I'll do this right after the 1.15 release, i.e. a week or so. Is this blocking you?

**Comment by DonFlymoor** [comment]
Yes. I can't download files larger then 40-60 MB, so when I try git clone, it fails.

**Comment by DonFlymoor** [comment]
Once I can clone this repository, I'll try to add support for ARM.

**Comment by GabrieleGiuseppini** [comment]
Hey, I've added all the huge files to git LFS. You may now clone the repo, and you can elect to not download the files stored under LFS (which you will *not* need for building, so you may safely ignore them), have a look at https://stackoverflow.com/questions/42019529/how-to-clone-pull-a-git-repository-ignoring-lfs.

I'm closing this ticket now. Glad to hear you're planning to add support for ARM! Before you get started, have a look at the repo and let me know how you plan on proceeding. Let's continue this conversation on the other issue.
