### ISSUE TITLE
On branch opengl_context_trick, 'UIControls/UnfocusablePanel.h' file not found

### ISSUE THREAD

**Issue by DonFlymoor** [GabrieleGiuseppini/Floating-Sandbox#37]
`UIControls/UnfocusablePanel.h` does not exist, but `UIControls/UnFocusablePanel.h` does.
The f is capitalized in the filename, but not in `Floating-Sandbox/SwitchboardPanel.h`

**Comment by GabrieleGiuseppini** [comment]
Thank you, fixed.
