### ISSUE TITLE
Green Lines

### ISSUE THREAD

**Issue by CatyMations** [GabrieleGiuseppini/Floating-Sandbox#38]
Hi, so i downloaded the game from gamejolt a few days ago, but for some reason these green lines stretch across the screen both blocking and distorting everything. 

I've tried reinstalling and repairing it multible times but nothing has yet worked.
Do you have any idea why this happens?

Screenshot:
![image](https://user-images.githubusercontent.com/67920477/86620456-a159df80-bfbc-11ea-9be0-f798766de992.png)

**Comment by GabrieleGiuseppini** [comment]
Hi, you have an Intel UHD graphics card, can you confirm?

**Comment by CatyMations** [comment]
> Hi, you have an Intel UHD graphics card, can you confirm?

Yes, An Intel UHD Graphics 620 to be exact.

**Comment by GabrieleGiuseppini** [comment]
There you go, thanks for checking!

A few months back a beta driver for this card came out and was included in a "Driver Pack", which is some sort of package that promises to keep people's boxes always up to date. However, the driver is a beta and has issues. You should revert to the latest official driver from Intel - if you're not Windows-savvy you may follow the steps at https://community.intel.com/t5/Graphics/video-playback-green-screen-with-Intel-HD-Graphics-4000/td-p/523312?profile.language=en.

Let me know how it goes!

**Comment by GabrieleGiuseppini** [comment]
I'm assuming my instructions did the trick. Feel free to reopen if you still need help with this issue.
