### ISSUE TITLE
Where is the anti-matter bomb sound from?

### ISSUE THREAD

**Issue by The-SamminAter** [GabrieleGiuseppini/Floating-Sandbox#39]
I was asked this question on discord, and no one on the fs dev server answered it, so I figured I’d ask it here:
> Do you know where the sound file with this ominous chorus comes from, which is triggered by ignition of the antimatter bomb?  It sounds so interesting and mystical-epic that I would really like to know the origin. 

Here is the audio file mentioned: [Antimatter-Bomb-Chorus.mp3](https://cdn.discordapp.com/attachments/730973104800661534/730973451799625768/Antimatter-Bomb-Chorus.mp3)

**Comment by GabrieleGiuseppini** [comment]
Hi,

First of all, that sample is two samples after each other - there's the sound of the pre-implosion (very short), followed by the sound of the implosion (the long, slowly-building choir). In any case, I've checked in my archives and couldn't find where the second one comes from - it was one of the very first sounds I've collected for Floating Sandbox :-) Sorry about that.
