### ISSUE TITLE
Game "Crashes" on Version: 1.16.4.1

### ISSUE THREAD

**Issue by TDRMinecraft** [GabrieleGiuseppini/Floating-Sandbox#51]
![grafik](https://user-images.githubusercontent.com/38729194/117573080-51fda780-b0d6-11eb-900a-ea2817b75b22.png)

I updated my Gameversion to 1.16.4.1 because of the Pop Up window inside of the Game. After the Update the game shows this "Error" - need help. Ask if you need more deatails please.

**Comment by GabrieleGiuseppini** [comment]
You should nuke completely the Data folder and re-copy it from scratch.

**Comment by TDRMinecraft** [comment]
I installed from GameJolt - complete reinstall has worked

**Comment by GabrieleGiuseppini** [comment]
Glad to hear that!
