### ISSUE TITLE
Game crashes when opening a ship.

### ISSUE THREAD

**Issue by Real-Luke-James** [GabrieleGiuseppini/Floating-Sandbox#52]
When I try to open a ship, the game just crashes with no explanation. Happens even after reinstall. I was able to capture a video of the issue. Version 1.16.4.1.

https://user-images.githubusercontent.com/79417248/118410988-300ca380-b647-11eb-817b-253c79cf0f06.mp4

**Comment by Real-Luke-James** [comment]
Here is the video with the options menu.

https://user-images.githubusercontent.com/79417248/118411046-972a5800-b647-11eb-806b-72c3ad88d251.mp4

**Comment by Real-Luke-James** [comment]
Here is the video with the options menu.

https://user-images.githubusercontent.com/79417248/118411232-5979ff00-b648-11eb-8b6b-0a171a5a7cbb.mp4

**Comment by GabrieleGiuseppini** [comment]
A couple of questions:
1. Is this from an official download from gamejolt, or is it a custom build instead?
2. Can you attach the dump file created at C:\users\<your user>\appdata\roaming\Floating Sandbox\Diagnostics?

**Comment by Real-Luke-James** [comment]
1. It is the official download from GameJolt.
2. There is no folder in that location.

**Comment by GabrieleGiuseppini** [comment]
Ok, let's do this then:
1. Uninstall the game
2. Go under C:\users\<your user>\appdata\local
3. Delete the "Floating Sandbox" folder
4. Go under C:\users\<your user>\appdata\roaming
5. Delete the "Floating Sandbox" folder
6. Re-install the game

Let me know if that worked.

**Comment by Real-Luke-James** [comment]
It did not work.

**Comment by GabrieleGiuseppini** [comment]
Did you see the folders at 3. and 5. above before deleting them? If yes, and the game still crashes after deleting those folders, then I can't help you - the issue you are having has nothing to do with the game but likely with your Windows installation being busted.
On the other hand, if you did *not* see the folders, then you're likely having troubles following the directions and hence there's still a chance it may be fixed.
Let me know if you did see the folders at 3. and 5. above.

**Comment by Real-Luke-James** [comment]
After Uninstalling the game, it removes the folder in AppData/Local.

**Comment by Real-Luke-James** [comment]
And after following the steps again, it still doesn't work

**Comment by GabrieleGiuseppini** [comment]
Thanks for trying that out again. This is a weird crash, FS doesn't even get the chance of writing a crash damp. Are you able to check whether Windows has created a crash damp itself? Also look at the Event Log, under Application - see if there's any mentions of a crash in FloatingSandbox.exe, with eventually the coordinates to a crash dump file.

**Comment by Real-Luke-James** [comment]
Here is the Windows Event Logs
[Crash Event.zip](https://github.com/GabrieleGiuseppini/Floating-Sandbox/files/6527276/Crash.Event.zip)

**Comment by GabrieleGiuseppini** [comment]
Thank you. What language is your computer on?

Have a look at this, I'm in good company - Microsoft's Flight Simulator crashes in the same way: https://forums.flightsimulator.com/t/ctd-on-accessing-options-general/400671

Can you make sure you have the English language pack installed? Please make sure your "Preferred Languages" screenshot looks exactly like the one in the thread, read the last message on how this solved the issue.

**Comment by Real-Luke-James** [comment]
1. My Language is on English
2. No, but I am in the Windows Insiders Program, if that makes a difference.

**Comment by Real-Luke-James** [comment]
Here is my build of Windows.
![Capture27](https://user-images.githubusercontent.com/79417248/119434617-685a5480-bccd-11eb-89b2-6a2727a35912.PNG)

**Comment by Real-Luke-James** [comment]
Ok. Thank You.

**Comment by Real-Luke-James** [comment]
Update: After updating Windows 10 to build 19043.1081, the bug is no longer exists.

**Comment by GabrieleGiuseppini** [comment]
Glad to hear that!

**Comment by Real-Luke-James** [comment]
And it also works on windows 10 21H2 Insider preview!
