### ISSUE TITLE
Add The Ability To Put 2 or 3 Ships In The same time

### ISSUE THREAD

**Issue by LouiIPSW** [GabrieleGiuseppini/Floating-Sandbox#56]
For example adding a titanic wreck and a submarine in the same time would be cool

and also i love floating sandbox and play it every day :)

**Comment by GabrieleGiuseppini** [comment]
Hi,
This is definitely the long term goal of Floating Sandbox. See the full roadmap at https://gamejolt.com/p/the-future-of-floating-sandbox-cdk2c9yi.

It will happen however only when collision detection will be added.
