### ISSUE TITLE
How To Make The File into A Game?

### ISSUE THREAD

**Issue by AutoBackNeck** [GabrieleGiuseppini/Floating-Sandbox#61]
Ok ok, I am very sorry and this may be wasting your time, but me and many others in my gaming community have been asking ourselves the same things, "How do we make it into a playable game?". I myself have been trying to figure this out and I am not a big computer person so I do not know much for coding and or files, but I sure do know how to play an Xbox XD. Ok but is it possible you can simply put a mini-guide on how to make the file playable? (I use windows, so if it is possible you can direct a tutorial for it also that would be awesome!) Thank you!

-AutoBackNeck

**Comment by GabrieleGiuseppini** [comment]
Hi AutoBackNeck, thanks so much for reaching to me for this question!
What do you mean exactly with "how to make the file playable"? Do you mean "how to make a ship file"?

**Comment by AutoBackNeck** [comment]
What I mean is that I cannot seems to play the game, I am sure I am missing something but when I try to find something to get the game started I find nothing, is there a specific way to make it playable?

**Comment by AutoBackNeck** [comment]
Oh wow, my grammar sucks sorry.

**Comment by AutoBackNeck** [comment]
:TO REPHRASE: Simply I wish to know how do I make the downloaded files that I downloaded directly from the "Zip" Source for v1.16.7 work, as in how do I go from the file itself and start playing the game. (and) If you do understand a bit better what I am trying to ask, if it requires me to download or open the file under a certain app, what app should I be using to open your "Zip" file for Floating Sandbox v.1.16.7 ?

**Comment by GabrieleGiuseppini** [comment]
OOH! I understand now!!! The zip only contains the source files! The actual game can be downloaded - for free - at www.gamejolt.com, just search for "Floating Sandbox"!
