### ISSUE TITLE
Disable "coasting" while zooming in or out (or add a zoom speed slider)

### ISSUE THREAD

**Issue by DanTheMann15** [GabrieleGiuseppini/Floating-Sandbox#70]
Hi there, i have a request to bring back the original zoom speed of floating sandbox, as the zoom coasting animation introduced in 1.17.3 is way too long and drawn-out. can you restore the previous zooming animation, or at least give us the ability to adjust the zoom speed?

it would help greatly with the experience.

**Comment by DanTheMann15** [comment]
i forgot to mention, the coasting makes me zoom in or out more than i wanted to. that's my chief problem.

**Comment by GabrieleGiuseppini** [comment]
Hi Dan, have you tried to disable auto-focus via the Control menu or via Ctrl^HOME? That should bring back the previous behavior. Let me know if that works out for you.

**Comment by DanTheMann15** [comment]
nope, it does not.

i turned it off upon updating but unfortunately it does not make a difference.

**Comment by GabrieleGiuseppini** [comment]
So you'd like to be able to make the zoom speed faster, correct?

**Comment by DanTheMann15** [comment]
my desire is to have the old behavior, but being able to control the zoom speed and whether or not it coasts would be great.

**Comment by GabrieleGiuseppini** [comment]
So wait, what do you mean exactly with "coasting"? That goes away when you disable auto-focus, right?

**Comment by DanTheMann15** [comment]
sorry for the delay;

Coasting is another word for "Inertial Scrolling", this google search sums it up nicely:
https://www.google.com/search?q=Kinetic+scrolling

in this case, it happens when i zoom in or out, it still has the inertia from zooming. hence it continues to zoom in or out even after i have stopped scrolling. it does not go away when i turn off auto-focus.

my tracpad on my laptop has coasting disabled so i have more granular control over scrolling, but something was introduced in the 1.17.3 update that changed the zooming behavior.

**Comment by GabrieleGiuseppini** [comment]
Hi Dan, 

so I've just added a "camera speed adjustment" setting that you may use to make camera movements faster, and I was about to ask you to give it a try when I re-read your last answer and realized that I might have been off-track here.

You say "hence it continues to zoom in or out even after I have stopped scrolling" - do you mean that it continues to do so for *longer than in the previous version* (i.e. it continues to do so for a second or two), or are you saying instead that it continues to do so forever?

**Comment by DanTheMann15** [comment]
having the ability to adjust camera speed is fantastic, but we also need the ability to disable coasting as well.

yes it continues to zoom (coast) even after i had stopped scrolling, it also zooms out much faster than it zooms in.

when zooming out, it also coasts for longer pretty much to the point where it zooms all the way out. but the amount of movement is proportional to how quickly you scroll to zoom in/out with your scrollwheel or tracpad gesture.

it's pretty self-explanatory when using a laptop or touchscreen, i am not sure about a scrollwheel on a mouse though.

**Comment by GabrieleGiuseppini** [comment]
I see - I'm not sure then that it's an issue with Floating Sandbox, smells more like an issue with your tracpad. Does this happen only when you zoom via the tracpad? Does it also happen when you zoom via the +/- buttons?

**Comment by DanTheMann15** [comment]
believe me i've tested my tracpad, it's not it. the behavior with the +/- buttons is also the same, still coasts upon releasing the buttons and is proportional to how long you hold (or mash) the buttons.

and zooming in is also considerably faster than zooming out, regardless of method.
i may need to reinstall 1.17.2 to get a reference.

**Comment by DanTheMann15** [comment]
ok, immediately upon downgrading to the previous release (1.17.2.4) the zoom behavior is significantly better.

it coasts for a second then stops very quickly instead of slowing the zoom gradually, which to me is close to ideal.
and zooming in or out are at similar speeds and strength, zooming in is still slightly faster though.

the same applies with the +/- buttons, much more granular control over your distance.

**Comment by GabrieleGiuseppini** [comment]
Got it, thanks for checking out.

Any chance you can record a video of the zooming?

**Comment by DanTheMann15** [comment]
god where does the time go...

On [Gamejolt](https://gamejolt.com/games/floating-sandbox/353572) you can't download old builds, but i managed to get 1.17.2.4 from https://cheapsaturday.itch.io/floatingsandbox

it's also a little harder to test different versions of the game when you can't have more than one install, i would suggest making a .zip file option available for portable installations if the user desires (this is off-topic though, it's up to you.)

i'll try to make a video capture as soon as i can, but my laptop is 11 years old and doesn't have great specs so i don't know if recording the screen while running Floating Sandbox will significantly affect performance.

if you are curious about my laptop's specs, it's a Toshiba Satellite L755-S5355 manufactured in September 2011.
over the years i had upgraded the processor, ram and switched from an HDD to an SSD.

CPU: Intel Core i7-2760QM - (originally a Pentium B950)
GPU: Intel HD Graphics 3000 - (on the last driver released.)
OS: Windows 7 SP1 64-bit
Memory: 8GB 2x4GB sticks - (originally 4GB 2x2GB sticks)
Storage: Samsung 860 EVO 500GB SSD - (originally a 500GB 5400 RPM HDD)

**Comment by GabrieleGiuseppini** [comment]
Hey, do you have a discord account? Got some private binaries that I'd like you to try out. Send me an e-mail to floating.sandbox.g2@gmail.com.

**Comment by GabrieleGiuseppini** [comment]
Closing, just reopen if not solved.
