### ISSUE TITLE
installer?

### ISSUE THREAD

**Issue by Sloth-on-meth** [GabrieleGiuseppini/Floating-Sandbox#71]
so i've been trying to play this game for days. why is there not just an installer, or a built release? it's like rocket science trying to play this game

**Comment by GabrieleGiuseppini** [comment]
Are you kidding me?
From the readme: https://gamejolt.com/games/floating-sandbox/353572

The GitHub repo is for the source code.

**Comment by Sloth-on-meth** [comment]
oh my god 

i am so stupid 

sorry

**Comment by GabrieleGiuseppini** [comment]
ROTFL, no worries :-)
