### ISSUE TITLE
Cannot run the game on Debian 11

### ISSUE THREAD

**Issue by slp8234-jonas** [GabrieleGiuseppini/Floating-Sandbox#73]
When attempting to run the game, it fails with the error “./FloatingSandbox: error while loading shared libraries: libjpeg.so.8: cannot open shared object file: No such file or directory”. I already have the latest version of libjpeg-dev installed via `apt install libjpeg-dev`. Is there something else I should do?

**Comment by slp8234-jonas** [comment]
Okay, I got it to load, but it required using dpkg to manually install libjpeg8 from the debian snapshot archive. Debian doesn’t directly provide libjpeg8 in it’s default repos, as it has been replaced by libjpeg9 and libjpeg62-turbo.

**Comment by GabrieleGiuseppini** [comment]
Hi, thanks for the info. It sounds like I might need to link libjpeg statically then. Did you build Floating Sandbox yourself, or did you instead download the Linux tar from GameJolt?

**Comment by GabrieleGiuseppini** [comment]
Actually, it turns out that most of the other media libraries (png, flac, vorbis, etc.) are also linked dynamically, so at this moment I'd rather not go through the hassle of finding out how to statically link libjpeg.
