### ISSUE TITLE
Game error on startup (Ubuntu 22.04)

### ISSUE THREAD

**Issue by nuggetsyun** [GabrieleGiuseppini/Floating-Sandbox#81]
OpenGL error, what do i do?
![Captura desde 2023-04-21 19-57-52](https://user-images.githubusercontent.com/131500897/233753369-9a9839c8-7c11-40a9-a2fe-8c0950636bc6.png)

**Comment by GabrieleGiuseppini** [comment]
Try updating your graphics card's drivers. Let me know if that solves the issue.

**Comment by GabrieleGiuseppini** [comment]
Hi, any news on this issue? I'll close if I don't hear from you.

**Comment by nuggetsyun** [comment]
Hello, no luck.

My drivers are up to date and its crashing with the same error.

**Comment by GabrieleGiuseppini** [comment]
It definitely seems you don't have OpenGL. Can you install the MESA drivers?  https://itsfoss.com/install-mesa-ubuntu/

**Comment by GabrieleGiuseppini** [comment]
BTW, the fix is simple: `export GDK_BACKEND=x11`.
