### ISSUE TITLE
screen freezes and the game crashes when the ship is about 50% full of water

### ISSUE THREAD

**Issue by gustavo99732** [GabrieleGiuseppini/Floating-Sandbox#83]
Just while I'm playing the game, when I'm going to sink the ship, **when the ship is almost 50% full of water the screen simply freezes and the game crashes** saying: floating sandbox is not responding: close the program or wait for the program to respond/work and this is happening with all versions even leaving the quality of the game very low.
**my operating system: windows 7**.
I ask please fix this bug

**Comment by GabrieleGiuseppini** [comment]
Hi, interesting - first time I hear about this. Does it happen all the time?

**Comment by GabrieleGiuseppini** [comment]
Also, another couple of questions:
1. Which version is this?
2. There is a dump file under %appdata%\Floating Sandbox\Diagnostics, could you send me that?

**Comment by gustavo99732** [comment]
it happens all the time on any ship, version; 1.18.0.4
the diagnosis is already a little old but it was when the game didn't crash completely, and it only came back after a little while, but now it crash completely. :
19/july/2023:
18:02:33.593813:Floating Sandbox 1.18.0.4 x86 32-bit Windows RELEASE (Jul  8 2023) @ 2023-07-19
18:02:33.593813:Windows timer resolution (min/max/cur): 15.600 / 0.500 / 15.600 ms
18:02:33.593813:Adjusted timer resolution: returned current=5000
18:02:33.593813:Windows timer resolution (min/max/cur): 15.600 / 0.500 / 0.500 ms
18:02:33.593813:Thread processor: 0
18:02:33.593813:ResourceLocator: argv0=C:\Users\Micro Pc\AppData\Local\Floating Sandbox\FloatingSandbox.exe rootPath="C:\\Users\\Micro Pc\\AppData\\Local\\Floating Sandbox" currentPath="C:\\Users\\Micro Pc\\AppData\\Local\\Floating Sandbox"
18:02:33.898048:Enforced language for desired identifier "<N/A>": "en"
18:02:33.924551:GLCanvas(100): ContentScaleFactor=1 DPIScaleFactor=1.25 100x100dip=125x125px
18:02:33.987559:OnMainGLCanvasResize: 1582x782 (Without GameController)
18:02:34.029565:GLCanvas(-1): ContentScaleFactor=1 DPIScaleFactor=1.25 100x100dip=125x125px
18:02:34.038566:SplashScreenDialog::Show(): Completed
18:02:34.077071:Loaded 699 structural materials.
18:02:34.081071:Loaded 97 electrical materials.
18:02:34.081571:TaskThread::TaskThread(): starting thread...
18:02:34.082071:Thread processor: 1
18:02:34.139079:MainFrame::MakeOpenGLContextCurrent()
18:02:34.140079:OpenGL version: 3.1
18:02:34.140079:GL_VENDOR=Intel
18:02:34.140079:GL_RENDERER=Intel(R) HD Graphics 2000
18:02:34.140079:Has GL_ARB_get_program_binary: NO
18:02:34.140079:Has GL_ARB_debug_output: NO
18:02:34.140079:GL_MAX_VERTEX_ATTRIBS=16
18:02:34.140079:GL_MAX_VIEWPORT_DIMS=8192x8192
18:02:34.140079:GL_MAX_TEXTURE_SIZE=8192
18:02:34.140079:GL_MAX_COMBINED_TEXTURE_IMAGE_UNITS=16
18:02:34.140079:GL_MAX_RENDERBUFFER_SIZE=4096
18:02:34.140079:AvoidGlFinish=1
18:02:34.140079:RenderContext: DoInvokeGlFinish=0
18:02:34.695649:Generic linear texture atlas size: (1024 x 512)
18:02:34.891674:Generic mipmapped texture atlas size: (4096 x 2048)
18:02:35.508252:Explosion texture atlas size: (4096 x 4096)
18:02:35.731281:Cloud texture atlas size: (2048 x 2048)
18:02:35.793789:Fish texture atlas size: (1024 x 1024)
18:02:36.705904:Font texture atlas size: (512 x 512)
18:02:37.493004:ThreadManager: isRenderingMultithreaded=YES maxSimulationParallelism=3 simulationParallism=3
18:02:37.493004:ThreadPool: creating thread pool with parallelism=3
18:02:37.493504:Thread processor: 0
18:02:37.493504:Thread processor: 0
18:02:37.509006:Next storm activating in 8222.7 seconds.
18:02:38.513634:CPU Calibration: iterationCount=230 score=1
18:02:38.513634:Graphics Calibration: score=0.131836
18:02:38.513634:ComputerCalibration: OceanRenderDetail=Advanced HeatRenderMode=Incandescence
18:03:02.297654:ShipLoadDialog::cctor(): creating wxGenericDirCtrl...
18:03:02.626696:ShipLoadDialog::cctor(): ...wxGenericDirCtrl created.
18:03:02.706206:ShipPreviewPanel::OnResized(674, 619 (client)): processing...
18:03:02.706206:ShipPreviewPanel::RecalculateGeometry(674, 619, 0): nCols=3 nRows=0 expHMargin=16 virtH=0
18:03:02.706206:ShipPreviewPanel::OnResized: ...processing completed.
18:03:02.709707:MainFrame::MakeOpenGLContextCurrent()
18:03:02.843223:LayoutOptimizer: 6533 perfect squares, 643 leftover points, 1292 leftover springs
18:03:02.854725:ShipFactory: Spring ACMR: original=0.52578, optimized=0.549956
18:03:02.901231:ShipStrengthRandomizer: completed randomization: numberOfCracks=93 time=39011us
18:03:02.909732:ShipFactory: Created ship: W=234, H=67, 7654raw/11752buf points, 27424 springs (6533 perfect squares, 95%), 13210 triangles, 1753 electrical elements, 4 frontiers.
18:03:02.910232:ShipFactory: Create() took 94268 us (frontiers: 1001 us)
18:03:02.932735:OnEngineControllerCreated(EEID=0:2 IID=0)
18:03:02.933235:OnPowerProbeCreated(EEID=0:4 IID=8): State=1
18:03:02.934235:OnSwitchCreated(EEID=0:463 IID=6): State=1
18:03:02.935235:OnSwitchCreated(EEID=0:465 IID=5): State=1
18:03:02.936235:OnSwitchCreated(EEID=0:1449 IID=4): State=1
18:03:02.937735:OnSwitchCreated(EEID=0:1457 IID=3): State=1
18:03:02.938736:OnSwitchCreated(EEID=0:1460 IID=2): State=1
18:03:02.939736:OnSwitchCreated(EEID=0:1461 IID=1): State=1
18:03:02.940736:OnSwitchCreated(EEID=0:1614 IID=9): State=0
18:03:02.942236:OnSwitchCreated(EEID=0:1686 IID=10): State=0
18:03:02.943236:OnEngineMonitorCreated(EEID=0:1699 IID=7): Thrust=0 RPM=0
18:03:02.943736:Layout: decoratedW=19, decoratedH=1, W=19 H=1
18:03:02.944736:OnMainGLCanvasResize: 1582x628 (With GameController)
18:03:02.946737:Post-Initialize took 28.9434s
18:03:02.946737:Game timer duration: 15
18:03:02.947237:MainFrame::OnPostInitializeIdle()
18:03:02.947737:Ship::RecalculateSpringRelaxationSpringForcesParallelism: springs=27424 simulationParallelism=3 springRelaxationParallelism=1
18:03:02.947737:Ship::RecalculateSpringRelaxationIntegrationAndSeaFloorCollisionParallelism: points=11752 simulationParallelism=3 actualParallelism=1
18:03:02.947737:Ship::RecalculateLightDiffusionParallelism: points=7656 simulationParallelism=3 lightDiffusionParallelism=3
18:03:03.132760:MainFrame::AfterGameRender: showing frame
18:03:03.142762:MainFrame::OnMainGLCanvasPaint(): rebinding OpenGLContext to main GL canvas, and hiding SplashScreen
18:03:03.142762:MainFrame::MakeOpenGLContextCurrent()
18:03:03.143762:GLCanvas::~GLCanvas()
18:03:13.251545:UpdateChecker: StatusCode=200
18:03:13.254546:UpdateChecker: LatestVersion=1.18.0.0
18:03:50.236742:MainFrame::OnQuit()
18:03:50.236742:MainFrame::OnMainFrameClose()
18:04:30.512356:GameController::~GameController()
18:04:30.512356:Thread exiting
18:04:30.512356:Thread exiting
18:04:30.512856:RenderContext::~RenderContext()
18:04:30.513356:TaskThread::~TaskThread(): signaled stop; waiting for thread now...
18:04:30.513356:TaskThread::ThreadLoop(): exiting
18:04:30.513356:TaskThread::~TaskThread(): ...thread stopped.
18:04:30.520357:OnMainGLCanvasResize: 1600x646 (Without GameController)
18:04:30.535859:MainFrame::~MainFrame()
18:04:30.626871:GLCanvas::~GLCanvas()

**Comment by gustavo99732** [comment]
> Also, another couple of questions:
> 
> 1. Which version is this?
> 2. There is a dump file under %appdata%\Floating Sandbox\Diagnostics, could you send me that?

it happens all the time on any ship, version; 1.18.0.4
the diagnosis is already a little old but it was when the game didn't crash completely, and it only came back after a little while, but now it crash completely. :
19/july/2023:
18:02:33.593813:Floating Sandbox 1.18.0.4 x86 32-bit Windows RELEASE (Jul 8 2023) @ 2023-07-19
18:02:33.593813:Windows timer resolution (min/max/cur): 15.600 / 0.500 / 15.600 ms
18:02:33.593813:Adjusted timer resolution: returned current=5000
18:02:33.593813:Windows timer resolution (min/max/cur): 15.600 / 0.500 / 0.500 ms
18:02:33.593813:Thread processor: 0
18:02:33.593813:ResourceLocator: argv0=C:\Users\Micro Pc\AppData\Local\Floating Sandbox\FloatingSandbox.exe rootPath="C:\Users\Micro Pc\AppData\Local\Floating Sandbox" currentPath="C:\Users\Micro Pc\AppData\Local\Floating Sandbox"
18:02:33.898048:Enforced language for desired identifier "<N/A>": "en"
18:02:33.924551:GLCanvas(100): ContentScaleFactor=1 DPIScaleFactor=1.25 100x100dip=125x125px
18:02:33.987559:OnMainGLCanvasResize: 1582x782 (Without GameController)
18:02:34.029565:GLCanvas(-1): ContentScaleFactor=1 DPIScaleFactor=1.25 100x100dip=125x125px
18:02:34.038566:SplashScreenDialog::Show(): Completed
18:02:34.077071:Loaded 699 structural materials.
18:02:34.081071:Loaded 97 electrical materials.
18:02:34.081571:TaskThread::TaskThread(): starting thread...
18:02:34.082071:Thread processor: 1
18:02:34.139079:MainFrame::MakeOpenGLContextCurrent()
18:02:34.140079:OpenGL version: 3.1
18:02:34.140079:GL_VENDOR=Intel
18:02:34.140079:GL_RENDERER=Intel(R) HD Graphics 2000
18:02:34.140079:Has GL_ARB_get_program_binary: NO
18:02:34.140079:Has GL_ARB_debug_output: NO
18:02:34.140079:GL_MAX_VERTEX_ATTRIBS=16
18:02:34.140079:GL_MAX_VIEWPORT_DIMS=8192x8192
18:02:34.140079:GL_MAX_TEXTURE_SIZE=8192
18:02:34.140079:GL_MAX_COMBINED_TEXTURE_IMAGE_UNITS=16
18:02:34.140079:GL_MAX_RENDERBUFFER_SIZE=4096
18:02:34.140079:AvoidGlFinish=1
18:02:34.140079:RenderContext: DoInvokeGlFinish=0
18:02:34.695649:Generic linear texture atlas size: (1024 x 512)
18:02:34.891674:Generic mipmapped texture atlas size: (4096 x 2048)
18:02:35.508252:Explosion texture atlas size: (4096 x 4096)
18:02:35.731281:Cloud texture atlas size: (2048 x 2048)
18:02:35.793789:Fish texture atlas size: (1024 x 1024)
18:02:36.705904:Font texture atlas size: (512 x 512)
18:02:37.493004:ThreadManager: isRenderingMultithreaded=YES maxSimulationParallelism=3 simulationParallism=3
18:02:37.493004:ThreadPool: creating thread pool with parallelism=3
18:02:37.493504:Thread processor: 0
18:02:37.493504:Thread processor: 0
18:02:37.509006:Next storm activating in 8222.7 seconds.
18:02:38.513634:CPU Calibration: iterationCount=230 score=1
18:02:38.513634:Graphics Calibration: score=0.131836
18:02:38.513634:ComputerCalibration: OceanRenderDetail=Advanced HeatRenderMode=Incandescence
18:03:02.297654:ShipLoadDialog::cctor(): creating wxGenericDirCtrl...
18:03:02.626696:ShipLoadDialog::cctor(): ...wxGenericDirCtrl created.
18:03:02.706206:ShipPreviewPanel::OnResized(674, 619 (client)): processing...
18:03:02.706206:ShipPreviewPanel::RecalculateGeometry(674, 619, 0): nCols=3 nRows=0 expHMargin=16 virtH=0
18:03:02.706206:ShipPreviewPanel::OnResized: ...processing completed.
18:03:02.709707:MainFrame::MakeOpenGLContextCurrent()
18:03:02.843223:LayoutOptimizer: 6533 perfect squares, 643 leftover points, 1292 leftover springs
18:03:02.854725:ShipFactory: Spring ACMR: original=0.52578, optimized=0.549956
18:03:02.901231:ShipStrengthRandomizer: completed randomization: numberOfCracks=93 time=39011us
18:03:02.909732:ShipFactory: Created ship: W=234, H=67, 7654raw/11752buf points, 27424 springs (6533 perfect squares, 95%), 13210 triangles, 1753 electrical elements, 4 frontiers.
18:03:02.910232:ShipFactory: Create() took 94268 us (frontiers: 1001 us)
18:03:02.932735:OnEngineControllerCreated(EEID=0:2 IID=0)
18:03:02.933235:OnPowerProbeCreated(EEID=0:4 IID=8): State=1
18:03:02.934235:OnSwitchCreated(EEID=0:463 IID=6): State=1
18:03:02.935235:OnSwitchCreated(EEID=0:465 IID=5): State=1
18:03:02.936235:OnSwitchCreated(EEID=0:1449 IID=4): State=1
18:03:02.937735:OnSwitchCreated(EEID=0:1457 IID=3): State=1
18:03:02.938736:OnSwitchCreated(EEID=0:1460 IID=2): State=1
18:03:02.939736:OnSwitchCreated(EEID=0:1461 IID=1): State=1
18:03:02.940736:OnSwitchCreated(EEID=0:1614 IID=9): State=0
18:03:02.942236:OnSwitchCreated(EEID=0:1686 IID=10): State=0
18:03:02.943236:OnEngineMonitorCreated(EEID=0:1699 IID=7): Thrust=0 RPM=0
18:03:02.943736:Layout: decoratedW=19, decoratedH=1, W=19 H=1
18:03:02.944736:OnMainGLCanvasResize: 1582x628 (With GameController)
18:03:02.946737:Post-Initialize took 28.9434s
18:03:02.946737:Game timer duration: 15
18:03:02.947237:MainFrame::OnPostInitializeIdle()
18:03:02.947737:Ship::RecalculateSpringRelaxationSpringForcesParallelism: springs=27424 simulationParallelism=3 springRelaxationParallelism=1
18:03:02.947737:Ship::RecalculateSpringRelaxationIntegrationAndSeaFloorCollisionParallelism: points=11752 simulationParallelism=3 actualParallelism=1
18:03:02.947737:Ship::RecalculateLightDiffusionParallelism: points=7656 simulationParallelism=3 lightDiffusionParallelism=3
18:03:03.132760:MainFrame::AfterGameRender: showing frame
18:03:03.142762:MainFrame::OnMainGLCanvasPaint(): rebinding OpenGLContext to main GL canvas, and hiding SplashScreen
18:03:03.142762:MainFrame::MakeOpenGLContextCurrent()
18:03:03.143762:GLCanvas::~GLCanvas()
18:03:13.251545:UpdateChecker: StatusCode=200
18:03:13.254546:UpdateChecker: LatestVersion=1.18.0.0
18:03:50.236742:MainFrame::OnQuit()
18:03:50.236742:MainFrame::OnMainFrameClose()
18:04:30.512356:GameController::~GameController()
18:04:30.512356:Thread exiting
18:04:30.512356:Thread exiting
18:04:30.512856:RenderContext::~RenderContext()
18:04:30.513356:TaskThread::~TaskThread(): signaled stop; waiting for thread now...
18:04:30.513356:TaskThread::ThreadLoop(): exiting
18:04:30.513356:TaskThread::~TaskThread(): ...thread stopped.
18:04:30.520357:OnMainGLCanvasResize: 1600x646 (Without GameController)
18:04:30.535859:MainFrame::~MainFrame()
18:04:30.626871:GLCanvas::~GLCanvas()

**Comment by gustavo99732** [comment]
> Also, another couple of questions:
> 
> 1. Which version is this?
> 2. There is a dump file under %appdata%\Floating Sandbox\Diagnostics, could you send me that?

problem solved: what breaks the game: air bubbles. bro generates many air bubbles

**Comment by gustavo99732** [comment]
> Also, another couple of questions:
> 
> 1. Which version is this?
> 2. There is a dump file under %appdata%\Floating Sandbox\Diagnostics, could you send me that?

1- version 1.18.0.4 but it happens with any version but I don't know which version this error started.
2- it happens with any ship and always.
18:02:33.593813:Floating Sandbox 1.18.0.4 x86 32-bit Windows RELEASE (Jul  8 2023) @ 2023-07-19
18:02:33.593813:Windows timer resolution (min/max/cur): 15.600 / 0.500 / 15.600 ms
18:02:33.593813:Adjusted timer resolution: returned current=5000
18:02:33.593813:Windows timer resolution (min/max/cur): 15.600 / 0.500 / 0.500 ms
18:02:33.593813:Thread processor: 0
18:02:33.593813:ResourceLocator: argv0=C:\Users\Micro Pc\AppData\Local\Floating Sandbox\FloatingSandbox.exe rootPath="C:\\Users\\Micro Pc\\AppData\\Local\\Floating Sandbox" currentPath="C:\\Users\\Micro Pc\\AppData\\Local\\Floating Sandbox"
18:02:33.898048:Enforced language for desired identifier "<N/A>": "en"
18:02:33.924551:GLCanvas(100): ContentScaleFactor=1 DPIScaleFactor=1.25 100x100dip=125x125px
18:02:33.987559:OnMainGLCanvasResize: 1582x782 (Without GameController)
18:02:34.029565:GLCanvas(-1): ContentScaleFactor=1 DPIScaleFactor=1.25 100x100dip=125x125px
18:02:34.038566:SplashScreenDialog::Show(): Completed
18:02:34.077071:Loaded 699 structural materials.
18:02:34.081071:Loaded 97 electrical materials.
18:02:34.081571:TaskThread::TaskThread(): starting thread...
18:02:34.082071:Thread processor: 1
18:02:34.139079:MainFrame::MakeOpenGLContextCurrent()
18:02:34.140079:OpenGL version: 3.1
18:02:34.140079:GL_VENDOR=Intel
18:02:34.140079:GL_RENDERER=Intel(R) HD Graphics 2000
18:02:34.140079:Has GL_ARB_get_program_binary: NO
18:02:34.140079:Has GL_ARB_debug_output: NO
18:02:34.140079:GL_MAX_VERTEX_ATTRIBS=16
18:02:34.140079:GL_MAX_VIEWPORT_DIMS=8192x8192
18:02:34.140079:GL_MAX_TEXTURE_SIZE=8192
18:02:34.140079:GL_MAX_COMBINED_TEXTURE_IMAGE_UNITS=16
18:02:34.140079:GL_MAX_RENDERBUFFER_SIZE=4096
18:02:34.140079:AvoidGlFinish=1
18:02:34.140079:RenderContext: DoInvokeGlFinish=0
18:02:34.695649:Generic linear texture atlas size: (1024 x 512)
18:02:34.891674:Generic mipmapped texture atlas size: (4096 x 2048)
18:02:35.508252:Explosion texture atlas size: (4096 x 4096)
18:02:35.731281:Cloud texture atlas size: (2048 x 2048)
18:02:35.793789:Fish texture atlas size: (1024 x 1024)
18:02:36.705904:Font texture atlas size: (512 x 512)
18:02:37.493004:ThreadManager: isRenderingMultithreaded=YES maxSimulationParallelism=3 simulationParallism=3
18:02:37.493004:ThreadPool: creating thread pool with parallelism=3
18:02:37.493504:Thread processor: 0
18:02:37.493504:Thread processor: 0
18:02:37.509006:Next storm activating in 8222.7 seconds.
18:02:38.513634:CPU Calibration: iterationCount=230 score=1
18:02:38.513634:Graphics Calibration: score=0.131836
18:02:38.513634:ComputerCalibration: OceanRenderDetail=Advanced HeatRenderMode=Incandescence
18:03:02.297654:ShipLoadDialog::cctor(): creating wxGenericDirCtrl...
18:03:02.626696:ShipLoadDialog::cctor(): ...wxGenericDirCtrl created.
18:03:02.706206:ShipPreviewPanel::OnResized(674, 619 (client)): processing...
18:03:02.706206:ShipPreviewPanel::RecalculateGeometry(674, 619, 0): nCols=3 nRows=0 expHMargin=16 virtH=0
18:03:02.706206:ShipPreviewPanel::OnResized: ...processing completed.
18:03:02.709707:MainFrame::MakeOpenGLContextCurrent()
18:03:02.843223:LayoutOptimizer: 6533 perfect squares, 643 leftover points, 1292 leftover springs
18:03:02.854725:ShipFactory: Spring ACMR: original=0.52578, optimized=0.549956
18:03:02.901231:ShipStrengthRandomizer: completed randomization: numberOfCracks=93 time=39011us
18:03:02.909732:ShipFactory: Created ship: W=234, H=67, 7654raw/11752buf points, 27424 springs (6533 perfect squares, 95%), 13210 triangles, 1753 electrical elements, 4 frontiers.
18:03:02.910232:ShipFactory: Create() took 94268 us (frontiers: 1001 us)
18:03:02.932735:OnEngineControllerCreated(EEID=0:2 IID=0)
18:03:02.933235:OnPowerProbeCreated(EEID=0:4 IID=8): State=1
18:03:02.934235:OnSwitchCreated(EEID=0:463 IID=6): State=1
18:03:02.935235:OnSwitchCreated(EEID=0:465 IID=5): State=1
18:03:02.936235:OnSwitchCreated(EEID=0:1449 IID=4): State=1
18:03:02.937735:OnSwitchCreated(EEID=0:1457 IID=3): State=1
18:03:02.938736:OnSwitchCreated(EEID=0:1460 IID=2): State=1
18:03:02.939736:OnSwitchCreated(EEID=0:1461 IID=1): State=1
18:03:02.940736:OnSwitchCreated(EEID=0:1614 IID=9): State=0
18:03:02.942236:OnSwitchCreated(EEID=0:1686 IID=10): State=0
18:03:02.943236:OnEngineMonitorCreated(EEID=0:1699 IID=7): Thrust=0 RPM=0
18:03:02.943736:Layout: decoratedW=19, decoratedH=1, W=19 H=1
18:03:02.944736:OnMainGLCanvasResize: 1582x628 (With GameController)
18:03:02.946737:Post-Initialize took 28.9434s
18:03:02.946737:Game timer duration: 15
18:03:02.947237:MainFrame::OnPostInitializeIdle()
18:03:02.947737:Ship::RecalculateSpringRelaxationSpringForcesParallelism: springs=27424 simulationParallelism=3 springRelaxationParallelism=1
18:03:02.947737:Ship::RecalculateSpringRelaxationIntegrationAndSeaFloorCollisionParallelism: points=11752 simulationParallelism=3 actualParallelism=1
18:03:02.947737:Ship::RecalculateLightDiffusionParallelism: points=7656 simulationParallelism=3 lightDiffusionParallelism=3
18:03:03.132760:MainFrame::AfterGameRender: showing frame
18:03:03.142762:MainFrame::OnMainGLCanvasPaint(): rebinding OpenGLContext to main GL canvas, and hiding SplashScreen
18:03:03.142762:MainFrame::MakeOpenGLContextCurrent()
18:03:03.143762:GLCanvas::~GLCanvas()
18:03:13.251545:UpdateChecker: StatusCode=200
18:03:13.254546:UpdateChecker: LatestVersion=1.18.0.0
18:03:50.236742:MainFrame::OnQuit()
18:03:50.236742:MainFrame::OnMainFrameClose()
18:04:30.512356:GameController::~GameController()
18:04:30.512356:Thread exiting
18:04:30.512356:Thread exiting
18:04:30.512856:RenderContext::~RenderContext()
18:04:30.513356:TaskThread::~TaskThread(): signaled stop; waiting for thread now...
18:04:30.513356:TaskThread::ThreadLoop(): exiting
18:04:30.513356:TaskThread::~TaskThread(): ...thread stopped.
18:04:30.520357:OnMainGLCanvasResize: 1600x646 (Without GameController)
18:04:30.535859:MainFrame::~MainFrame()
18:04:30.626871:GLCanvas::~GLCanvas()

**I think I solved the problem, I removed the air bubbles and it improved a lot, now the screen just freezes for a little while but maybe that only happened today like a few days ago.**

**Comment by GabrieleGiuseppini** [comment]
Thank you. Actually, the file under %appdata%\Floating Sandbox\Diagnostics is a ".dmp" file, could you send me that one?

**Comment by gustavo99732** [comment]
> Thank you. Actually, the file under %appdata%\Floating Sandbox\Diagnostics is a ".dmp" file, could you send me that one?

the game crashed again, I already gave up trying to play

**Comment by GabrieleGiuseppini** [comment]
Hi, I'm sorry to hear that. Would you be willing to help me out debugging this issue? If yes you'll gain eternal recognition in the Credits section of the game!

**Comment by gustavo99732** [comment]
> Olá, lamento ouvir isso. Você estaria disposto a me ajudar a depurar esse problema? Se sim, você ganhará reconhecimento eterno na seção de Créditos do jogo!

Sorry but no, I'm just wanting to play the game without serious errors. sorry

**Comment by GabrieleGiuseppini** [comment]
Ok, fair enough. Closing then.
