### ISSUE TITLE
error while loading shared libraries: libFLAC.so.8

### ISSUE THREAD

**Issue by PavelDobCZ23** [GabrieleGiuseppini/Floating-Sandbox#88]
Running the Linux version of the game crashes with the following error: 
`error while loading shared libraries: libFLAC.so.8: cannot open shared object file: No such file or directory`
I am on Fedora 39 and have `flac` installed, however after further inspection, it seems that the only libFLAC files available in lib folders are `libFLAC.so.12` and `libFLAC.so.12.1.0`.

**Comment by GabrieleGiuseppini** [comment]
Hi, thank you for your report!

Indeed, the Linux build was done with flac 8. Can you install flac 8 and try again? On Fedora that should be the 1.3.2 package, see also https://koji.fedoraproject.org/koji/packageinfo?packageID=741 for more information. Please let me know if that works - if so I'll add it to the FAQ (together with a thank you note for you!)

**Comment by PavelDobCZ23** [comment]
> Hi, thank you for your report!
> 
> Indeed, the Linux build was done with flac 8. Can you install flac 8 and try again? On Fedora that should be the 1.3.2 package, see also [koji.fedoraproject.org/koji/packageinfo?packageID=741](https://koji.fedoraproject.org/koji/packageinfo?packageID=741) for more information. Please let me know if that works - if so I'll add it to the FAQ (together with a thank you note for you!)

I don't think that's a viable solution, I am on Fedora 39 and the version you suggest was last built for Fedora 31. Even if I tried to install it, there'd be dependency conflicts and it would result in mismatches across packages. Could you not statically link the library if you need to use such an old version? You can't expect people to use ancient version of dependencies running on currently supported recent systems.

**Comment by GabrieleGiuseppini** [comment]
You're right, but unfortunately FS is not the one requiring flac-lib, it's SFML doing that (which FS statically links with). I'll see if there's a way to statically link with SFML and _still_ take its dependencies as dyn libs.
Alternatively, I could try to release a FS build with SFML as dynamic - do you have the possibility of installing the SFML dyn libs? If so, which versions are they?

**Comment by PavelDobCZ23** [comment]
> You're right, but unfortunately FS is not the one requiring flac-lib, it's SFML doing that (which FS statically links with). I'll see if there's a way to statically link with SFML and _still_ take its dependencies as dyn libs.
> Alternatively, I could try to release a FS build with SFML as dynamic - do you have the possibility of installing the SFML dyn libs? If so, which versions are they?

It is possible to install SFML as a package, the version on Fedora 39 is [2.5.1-15](https://packages.fedoraproject.org/pkgs/SFML/SFML/fedora-39.html). Most Linux distros [seem to ship version](https://repology.org/project/sfml/versions) 2.5.x or 2.6.x. Also thank you for investing your time into dealing with this issue.

**Comment by GabrieleGiuseppini** [comment]
Ok, I'm halfway-through with taking SFML as a dynamic dependency, but I'm on Ubuntu 18 and I can only get 2.4.2 on it, which won't work with FS as I need some 2.5 features.
I'll be upgrading my Ubuntu to 20 and try with that. Stay tuned,

**Comment by PavelDobCZ23** [comment]
Thx for your efforts, I am excited to be able to play without any issues. 👍

**Comment by GabrieleGiuseppini** [comment]
And finally, could you try this build please? https://drive.google.com/file/d/1Kw0imSzcPZVLVsNvkTQA_lUzT-XczE6Z/view?usp=drive_link

**Comment by PavelDobCZ23** [comment]
> And finally, could you try this build please? [drive.google.com/file/d/1Kw0imSzcPZVLVsNvkTQA_lUzT-XczE6Z/view?usp=drive_link](https://drive.google.com/file/d/1Kw0imSzcPZVLVsNvkTQA_lUzT-XczE6Z/view?usp=drive_link)

I am happy to say that after installing SFML, there is no problem with loading any shared libraries and the game successfully loads.

**Comment by GabrieleGiuseppini** [comment]
Fantastic, thank you so much. Closing now.
