### ISSUE TITLE
Unknown error while modifying electicial propreties of the electricial panel.

### ISSUE THREAD

**Issue by Drabelio1** [GabrieleGiuseppini/Floating-Sandbox#90]
![2024-11-30](https://github.com/user-attachments/assets/ab4b701c-9f85-4b54-8598-687758aa2259)
A bug happened to me in ShipBuilder of Floating Sandbox, while just doing some renaming and some copy pasting of the same named electricial elements already presents and deleting the original ones and then moving their positions number in the electricial panel. Then when loading it after saving all without error the changes weren't set but when coming back in the shipbuilder editor to see if they were changed like I changed them I got this error and then it kicked me back in the Floating Sandbox game and then the game stopped responding and crashed with the same error, my ship I built cannot be accessed due to this error stopping me from loading the ship and the game ( only for this ship as it is the only one to have this error). I suspect this as the cause as nothing else seemed wrong, but even myself isn't sure if it was this. A big sneaky bug for a specified action.

**Comment by Drabelio1** [comment]
The ship I made was Lysur and I spent 5 hours working on it and drawing everything and making it able to function. It was almost done, now my work seems lost for the time being.

**Comment by Drabelio1** [comment]
The bug still is there, I tried many times even with the update, it's kind of not allowing me to open it in any way. And how to send the ship file again? Already forgot about this.

**Comment by Drabelio1** [comment]
[Lysur.zip](https://github.com/user-attachments/files/17967000/Lysur.zip)
I figured it out myself

**Comment by Drabelio1** [comment]
Well for the how to send it not the bug obsiously.

**Comment by GabrieleGiuseppini** [comment]
Hi, here's your ship fixed. You only need to adjust the electrical panel for four missing elements.
[Lysur.zip](https://github.com/user-attachments/files/17969815/Lysur.zip)

The bug that caused this to happen should have been fixed in the last update (1.19.0), so do continue to use this last update. I'm closing the bug now, please reopen if this happen again to you with a 1.19.

**Comment by Drabelio1** [comment]
I had to get back to the previous version as even the fix didn't seemed to
work and same error again, for me, but no problem because I have the entire
work back, no worries now, atleast. I already thought of this idea but was
scared it would mess things up or anything but no.
